version: "3.2"

networks:
  pyton_flask_rest_api:

services:

  python:
    container_name: python
    build:
      context: './app/'
    ports:
      - "5002:5002"
    volumes:
      - ./app:/app
    networks:
      - pyton_flask_rest_api

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "98:80"
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - python
    networks:
      - pyton_flask_rest_api

  mysql_python:
    container_name: mysql_python
    image: arm64v8/mysql:oracle
    ports:
      - "33062:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always # restart unless stopped manually
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_ROOT_HOST: "%"
    networks:
      - pyton_flask_rest_api

  phpmyadmin:
    container_name: phpmyadmin_python
    image: arm64v8/phpmyadmin
    restart: always
    environment:
      PMA_HOST: docker.for.mac.localhost
      PMA_PR: https
      PMA_PORT: 33062
      PMA_USER: root
      PMA_PASSWORD: pwd
    ports:
      - "8099:80"
    networks:
      - pyton_flask_rest_api